### ISSUE TITLE
#define MICROSECOND misnomer in librethinkdbxx/src/net.h

### ISSUE THREAD

**Issue by iamorphen** [AtnNn/librethinkdbxx#27]
`librethinkdbxx/src/net.h` defines MICROSECOND [as 100 nanoseconds](https://github.com/AtnNn/librethinkdbxx/blob/master/src/net.h#L15). Unless I misunderstand the context, this is not intentional.

`#define MICROSECOND 0.0000001`
`0.0000001` should be `0.000001`.

**Comment by AtnNn** [comment]
Thanks for reporting that! Fixed in 15b527a

**Comment by iamorphen** [comment]
Thanks for your work on the driver! ( :
