### ISSUE TITLE
write_datum in namespace RethinkDB is missing

### ISSUE THREAD

**Issue by sushanttripathy** [AtnNn/librethinkdbxx#29]

**Comment by mbroadst** [comment]
@sushanttripathy all the json-related methods were made internal, could you help describe your use case for needing this method publicly?

**Comment by mbroadst** [comment]
@sushanttripathy maybe you're looking for something like this: https://github.com/AtnNn/librethinkdbxx/blob/master/src/datum.cc#L410 ?

**Comment by sushanttripathy** [comment]
Hi Matt,

Thanks for the quick response. I was unaware of the change. :)  I was
merely trying to run the associated example in the readme markdown.

Best,
Sushant

**Comment by mbroadst** [comment]
@sushanttripathy ah! thank you very much for that, I forgot to make the change there.
