### ISSUE TITLE
Adding a Geo Reference

### ISSUE THREAD

**Issue by CCJH** [AtnNn/librethinkdbxx#32]
Is there anyway to add a point to an object without calling run i.e.

`RethinkDB::Object({{"TS", RethinkDB::Time(newdata->fix.time)},{"POS", RethinkDB::point(newdata->fix.latitude, newdata->fix.longitude))}})`

Instead of

`RethinkDB::Object({{"TS", RethinkDB::Time(newdata->fix.time)},{"POS", RethinkDB::point(newdata->fix.latitude, newdata->fix.longitude).run(*Conn())}})`

**Comment by mbroadst** [comment]
@CCJH geo types are not presently (fully) implemented, but contributions are very much welcome.

**Comment by AtnNn** [comment]
You can use the internal representation of geometry objects. If it were implemented, this is what `R::Point` would map to:

```
{
  '$reql_type$': 'GEOMETRY',
  'type': 'Point',
  'coordinates': [0, 0]
}
```

**Comment by CCJH** [comment]
That works great, thanks.
