### ISSUE TITLE
Replacing documents

### ISSUE THREAD

**Issue by Maarten-p** [AtnNn/librethinkdbxx#4]
Is the replace() command already implemented? And what is the type of the JSON object that needs to be used as input? I tried a normal string but that didn't work. It would be nice if you could put up an example where you add something to the database.

**Comment by AtnNn** [comment]
The `replace` command is implemented and can be used just like [in Python](http://rethinkdb.com/api/python/replace/).

There are many ways of constructing an object that can be passed to `replace`: 

* The [`object`](http://rethinkdb.com/api/python/object/) command: `R::object("id", 2, "a", 5)`
* The [`json`](http://rethinkdb.com/api/python/json/) command: `R::json("{\"id\":2,\"a\":5}")`
* as a literal: `map<string, double>{{"id", 2}, {"a", 5}}`
